server.port: 8090
spring.jackson.default-property-inclusion: non_empty

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/drug-store

